### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by v-kolesnikov** [v-kolesnikov/dotfiles#11]
# Project
- [x] Add CI integration
- [ ] Write detailed README.md
- [ ] Screnshots\asciinema

---
# Vim
### Plugins
- [x] https://github.com/terryma/vim-multiple-cursors
- [ ] [sheerun/vim-polyglot](https://github.com/sheerun/vim-polyglot)
- [ ] moll/vim-bbye
- [ ] https://github.com/MattesGroeger/vim-bookmarks
- [ ] AndrewRadev/undoquit.vim
- [x] spell checking
- [ ] tpope/vim-unimpaired
- [ ] snoe/nvim-parinfer.js
### Rails
- [x] Run tests in Dispath

---
# RC files
- [ ] [ackrc](https://github.com/ai/environment/blob/master/ackrc)
- [ ] irbrc
# Clojure
### Libraries
- [ ] zcaudate/vinyasa

---
# Git
- [x] Fix git config (git ignore global)
- [ ] Configurable config

---
# Bash
- [x] export EDITOR='vim'
- [ ] `setxkbmap -layout us -option ctrl:nocaps`

---
# Vagrant
- [x] Add Vagrantfile for create box with dotfiles
- [x] Add default Vagrantfile
- [ ] `sudo apt-get install nfs-kernel-server nfs-common`
### Plugins:
- [ ] vagrant plugin install vagrant-vbguest
- [ ] vagrant plugin install vagrant-landrush

---
# Packages
- [x] Git
- [x] htop
- [x] httpie
- [x] exuberant-ctags
- [x] silver-searcher-ag
